### ISSUE TITLE
Expressions in Coverage XML files are not escaped

### ISSUE THREAD

**Issue by nrother** [amiq-consulting/fc4sc#13]
The following coverpoint will cause an invalid XML file to be created:
```c
COVERPOINT(int, result_cvp, opA & opB) {
    bin<int>("zero", 0),
    bin<int>("not_zero", interval(1,INT_MAX))
};
```
This is a snipped from the XML file:
```xml
<ucis:coverpoint name="result_cvp" key="KEY" exprString="opA & opB">
<ucis:options weight="1" goal="100" comment="" at_least="1" auto_bin_max="10" detect_overlap="0" />
<ucis:coverpointBin name="zero" 
type="default" alias="0">
<ucis:range 
from="0" 
to ="0"
>
<ucis:contents coverageCount="0"></ucis:contents>
</ucis:range>
```
Please note the invalid usage of a unescaped ampersand.

**Comment by nrother** [comment]
Unfortunately, not even resorting to C++ digraphs helps :frowning_face: 
```c
COVERPOINT(int, result_cvp, opA bitand opB) {
```

**Comment by amiq-consulting** [comment]
Hi nrother,

Thank you for posting this issue. I have fixed the problem in commit [https://github.com/amiq-consulting/fc4sc/commit/e38090e88b79e13affbdc257040f43cda9456856](https://github.com/amiq-consulting/fc4sc/commit/e38090e88b79e13affbdc257040f43cda9456856). I have tested it with your example and it should now be working.

Best Regards.
