### ISSUE TITLE
Coverage Report Script does not work

### ISSUE THREAD

**Issue by nrother** [amiq-consulting/fc4sc#15]
Error message:
```
Traceback (most recent call last):
  File "./fc4sc/tools/coverage_report/report.py", line 66, in <module>
    d = parser.get_report_data(args.xml_report)
AttributeError: UCIS_DB_Parser instance has no attribute 'get_report_data'
```
As far as I can see, the type `UCIS_DB_Parser` from `merge.py` actually has no such method.

**Comment by amiq-consulting** [comment]
Hi nrother,

Thank you for the issue. You are correct. 
The report script is not documented or tested yet. The missing functions were removed from the merge.py python module in a previous commit.
I have fixed the problem: [https://github.com/amiq-consulting/fc4sc/commit/1b4ddef0b41b468ccad2d2e830cf9a4ed659e425](https://github.com/amiq-consulting/fc4sc/commit/1b4ddef0b41b468ccad2d2e830cf9a4ed659e425).

Best Regard.
