### ISSUE TITLE
Generated UCIS Document Doesn't Match UCIS XSD for "instanceCoverages"

### ISSUE THREAD

**Issue by MarkTakaWilliams** [amiq-consulting/fc4sc#4]
UCIS document produces the instanceCoverages without the 'ucis:' namespacing tag

**Comment by MarkTakaWilliams** [comment]
Also when generating coverpointBin cannot have the attribute "name" and all references to "file" and "line" must be positive integers within the "id" tags.

**Comment by amiq-consulting** [comment]
Hi Mark,

Thank you for your feedback.

> UCIS document produces the instanceCoverages without the 'ucis:' namespacing tag

This is now fixed under the [cov_merge_tool](https://github.com/amiq-consulting/fc4sc/tree/cov_merge_tool) branch and will be available once the branch will be integrated into master.

> when generating coverpointBin cannot have the attribute "name"

According to the [UCIS DB](http://www.accellera.org/images/downloads/standards/ucis/UCIS_Version_1.0_Final_June-2012.pdf) documentation, the XSD for the coverpointBin element is as follows:
```xml
<xsd:complexType name="COVERPOINT_BIN">
    <xsd:sequence>
        <xsd:choice>
            <xsd:element name="range" type="RANGE_VALUE"
minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="sequence" type="SEQUENCE"
minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:element name="userAttr" type="USER_ATTR"
minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="key" type="xsd:string" use=”required”/>
    <xsd:attribute name="alias" type="xsd:string"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
</xsd:complexType>
```

And an example:
```xml
<coverpointBin name="UOR_name" key="0" alias="my_cv_bin" type="ignore">
    <range from="20" to="88">
        <contents coverageCount="0"></contents>
    </range>
    <userAttr key="string" type="str" > Not needed </userAttr>
</coverpointBin>
```

> all references to "file" and "line" must be positive integers within the "id" tags

This is an issue that has to be investigated. There are multiple things related to the UCIS DB schema which have to be handled properly. At the moment, the UCIS DB support is minimal and tailored to work with the tools that FC4SC provides. We are planning to add proper support for the UCIS DB schema in the future.

Best Regards
